version: 2

sources:
  - name: airbnb
    schema: dev
    tables:
      - name: listings
        identifier: raw_listings
      
      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 24
            period: hour
          
        loaded_at_field: "date"
       
